version: '3.9' 

services:
  php-env:
    build: . #path to dockerfile
    volumes: 
      - ./src:/var/www/html 
    ports:
      - 8080:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes: 
      - /var/lib/docker/volumes/volume1
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
